fortran_compiler:           # [win]
  - flang                   # [win]
fortran_compiler_version:   # [win]
  - 19                      # [win]

channel_targets:
  - conda-forge llvm_rc

channel_sources:
  - conda-forge,conda-forge/label/llvm_rc
