c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]    
  - clang_bootstrap  # [osx]

fortran_compiler:           # [win]
  - flang                   # [win]
fortran_compiler_version:   # [win]
  - 18                      # [win]

channel_targets:
  - conda-forge llvm_rc

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge
