cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]
c_compiler:          # [osx]
  - clang_bootstrap  # [osx]

channel_targets:
  - conda-forge llvm_rc

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge
