c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2019           # [win]
cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2019           # [win]

channel_targets:
  - conda-forge llvm_rc

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge
