{% set version = "19.0.0.dev0" %}
# check https://clang.llvm.org/docs/OpenMPSupport.html
# occasionally to see last fully supported openmp ver.
{% set openmp_ver = "4.5" %}

package:
  name: openmp
  version: {{ version }}

source:
  # url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version.replace(".rc", "-rc") }}.tar.gz 
  url: https://github.com/llvm/llvm-project/archive/3bb25636414ee5b5eaf99c0bdcc191052c9d7ffb.tar.gz
  sha256: 72bb3117472025b4e6a6fd6b04041abc735fedbe7f023e56c0413c0cfeb3ca0c
  # name folder for easier deletion; we do the equivalent of downloading
  # the subproject sources, so the work folder then has openmp in it;
  # for details see build scripts
  folder: llvm-project
  patches:
    # backport https://github.com/llvm/llvm-project/pull/80174
    - patches/0001-openmp-On-Windows-fix-standalone-cmake-build.patch
    # intermediate fix for https://github.com/llvm/llvm-project/issues/54596
    - patches/0002-link-libomp-to-compiler-rt-on-osx-arm.patch

build:
  number: 3

outputs:
  - name: llvm-openmp
    script: build-pkg.sh   # [unix]
    script: build-pkg.bat  # [win]
    build:
      # due to https://github.com/conda/conda-build/issues/5403
      overlinking_ignore_patterns:  # [ppc64le]
        - "**"                      # [ppc64le]
      ignore_run_exports:
        - libgcc-ng
        - libstdcxx-ng
        - _openmp_mutex
      run_exports:
        strong:
          - {{ pin_subpackage("llvm-openmp", max_pin=None) }}
          - _openmp_mutex >={{ openmp_ver }}  # [linux]
          - _openmp_mutex * *_llvm            # [linux]
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("cxx") }}
        # build cycle on osx: gfortran_{plat} -> libgfortran5 -> llvm-openmp
        - {{ compiler("fortran") }}  # [not osx]
        - clang  # [win]
        - cmake
        - ninja
        - perl
      host:
        - llvmdev {{ version }}|{{ version }}.*
        - zlib   # [linux]
        - zstd   # [linux]
        # see https://github.com/llvm/llvm-project/issues/54596
        - compiler-rt  # [osx and arm64]
      run_constrained:
        - openmp {{ version }}|{{ version }}.*
    test:
      requires:
        - clangxx
        - {{ compiler('cxx') }}
      files:
        - omp_hello.c
      commands:
        # headers
        - test -f $PREFIX/include/omp.h                   # [unix]
        - test -f $PREFIX/include/omp_lib.mod             # [linux]
        - if not exist %LIBRARY_INC%\omp.h exit 1         # [win]
        - if not exist %LIBRARY_INC%\omp_lib.mod exit 1   # [win]

        # shared library
        - test -f $PREFIX/lib/libomp.so                   # [linux]
        - test -f $PREFIX/lib/libomp.dylib                # [osx]
        - if not exist %LIBRARY_BIN%\libomp.dll exit 1    # [win]
        - if not exist %LIBRARY_LIB%\libomp.lib exit 1    # [win]

        # compilation test
        - export LNK_XTRA="-Wl,--allow-shlib-undefined"   # [linux]
        - $PREFIX/bin/clang -v -fopenmp -I$PREFIX/include -L$PREFIX/lib -Wl,-rpath,$PREFIX/lib $LNK_XTRA omp_hello.c -o omp_hello  # [unix]
        - '%LIBRARY_BIN%\clang -v -fopenmp -I%LIBRARY_INC% -L%LIBRARY_LIB% omp_hello.c -o omp_hello.exe'   # [win]
        - ./omp_hello            # [unix]
        - '%cd%\omp_hello.exe'   # [win]

about:
  home: http://openmp.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: openmp/LICENSE.TXT
  summary: The OpenMP API supports multi-platform shared-memory parallel programming in C/C++ and Fortran.
  dev_url: https://github.com/llvm/llvm-project/

extra:
  recipe-maintainers:
    - inducer
    - jakirkham
    - yesimon
    - isuruf
    - beckermr
    - katietz
    - h-vetinari
