{% set version = "13.0.1" %}
{% set openmp_ver = "4.5" %}

package:
  name: openmp
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/openmp-{{ version.replace(".rc", "rc") }}.src.tar.xz
  sha256: 6b79261371616c31fea18cd3ee1797c79ee38bcaf8417676d4fa366a24c96b4f
  patches:
    - f1b9ce2736d826df2ff4cbd67116864f0856334f.patch

build:
  number: 0
  skip: true  # [win and vc<14]

outputs:
  - name: llvm-openmp
    script: build-llvm-openmp.sh  # [not win]
    script: bld-llvm-openmp.bat  # [win]
    build:
      ignore_run_exports:
        - libgcc-ng
        - libstdcxx-ng
        - _openmp_mutex
      run_exports:
        strong:
          - {{ pin_subpackage("llvm-openmp", max_pin=None) }}
          - _openmp_mutex >={{ openmp_ver }}  # [linux]
          - _openmp_mutex * *_llvm            # [linux]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - clang  # [win]
        - cmake
        - make   # [unix]
        - perl
        - ninja  # [win]
      host:
        - llvmdev {{ version }}|{{ version }}.*
      run_constrained:
        - clangdev {{ version }}|{{ version }}.*
        - llvmdev {{ version }}|{{ version }}.*
        - openmp {{ version }}|{{ version }}.*
    test:
      requires:
        - clangxx
        - {{ compiler('cxx') }}
      commands:
        - if not exist %LIBRARY_BIN%\\libomp.dll exit 1   # [win]
        - test -f $PREFIX/lib/libomp.so                   # [linux]
        - test -f $PREFIX/lib/libomp.dylib                # [osx]
        - if not exist %LIBRARY_LIB%\\libomp.lib exit 1   # [win]
        - if not exist %LIBRARY_INC%\\omp.h exit 1        # [win]
        - test -f $PREFIX/include/omp.h                   # [unix]
        - $PREFIX/bin/clang -v -fopenmp -I$PREFIX/include -L$PREFIX/lib -Wl,-rpath,$PREFIX/lib omp_hello.c -o omp_hello  # [not win]
        - '%LIBRARY_BIN%\clang -v -fopenmp -I%LIBRARY_INC% -L%LIBRARY_LIB% omp_hello.c -o omp_hello.exe'   # [win]
        - ./omp_hello            # [unix]
        - '%cd%\omp_hello.exe'   # [win]
      files:
        - omp_hello.c

about:
  home: http://openmp.llvm.org/
  license: NCSA
  license_file: LICENSE.txt
  summary: The OpenMP API supports multi-platform shared-memory parallel programming in C/C++ and Fortran.

extra:
  recipe-maintainers:
    - inducer
    - jakirkham
    - yesimon
    - isuruf
    - beckermr
    - katietz
