{% set name = "llvm-openmp" %}
{% set version = "9.0.0" %}
{% set sha256 = "9979eb1133066376cc0be29d1682bc0b0e7fb541075b391061679111ae4d3b5b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://releases.llvm.org/{{ version }}/openmp-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]

test:
  requires:
    - clangdev
    - {{ compiler('cxx') }}  # [unix]
    - vs2017_{{ target_platform }}  # [win]
  commands:
    - if not exist %LIBRARY_BIN%\\libomp.dll exit 1   # [win]
    - test -f $PREFIX/lib/libomp.so                   # [linux]
    - test -f $PREFIX/lib/libomp.dylib                # [osx]
    - if not exist %LIBRARY_LIB%\\libomp.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\\omp.h exit 1        # [win]
    - test -f $PREFIX/include/omp.h                   # [unix]
    - $PREFIX/bin/clang -v -fopenmp -I$PREFIX/include -L$PREFIX/lib -Wl,-rpath,$PREFIX/lib omp_hello.c -o omp_hello  # [not win]
    - "%LIBRARY_BIN%\\clang -v -fopenmp -I%LIBRARY_INC% -L%LIBRARY_LIB% omp_hello.c -o omp_hello.exe"  # [win]
    - ./omp_hello            # [unix]
    - "%cd%\\omp_hello.exe"  # [win]
  files:
    - omp_hello.c

outputs:
  - name: llvm-openmp
    script: build-llvm-openmp.sh  # [not win]
    script: bld-llvm-openmp.bat   # [win]
    build:
      run_exports:
        strong:
          - {{ pin_subpackage("llvm-openmp", max_pin=None) }}
    requirements:
      build:
        - {{ compiler('cxx') }}  # [unix]
        - vs2017_{{ target_platform }}  # [win]
        - cmake
        - perl
        - ninja  # [win]
      host:
        - llvmdev {{ version }}|{{ version }}.*
      run_constrained:
        - clangdev {{ version }}|{{ version }}.*
        - llvmdev {{ version }}|{{ version }}.*
        - openmp {{ version }}|{{ version }}.*

about:
  home: http://openmp.llvm.org/
  license: NCSA
  license_file: LICENSE.txt
  summary: The OpenMP API supports multi-platform shared-memory parallel programming in C/C++ and Fortran.

extra:
  recipe-maintainers:
    - inducer
    - jakirkham
    - yesimon
    - isuruf
