build_platform: {osx_arm64: osx_64}
channel_priority: flexible
conda_forge_output_validation: true
provider: {linux_aarch64: azure, linux_ppc64le: azure}
test_on_native_only: true
conda_build:
  pkg_format: '2'
