bot:
  abi_migration_branches:
  - 21.x
  - 20.x
  - 19.x
build_platform:
  linux_ppc64le: linux_64
  win_arm64: win_64
# we need to sort llvm_rc after the main channel to avoid old rc-compilers
channel_priority: flexible
conda_build:
  error_overlinking: true
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  osx_arm64: default
test: native_and_emulated
workflow_settings:
  build_workspace_dir:
    - value: C:\bld
      os: win
  tools_install_dir:
    - value: C:\Miniforge
      os: win
