bot:
  abi_migration_branches:
  - 15.x
  - 14.x
build_platform: {osx_arm64: osx_64, linux_ppc64le: linux_64, linux_aarch64: linux_64}
# label/llvm_rc would overrule our default compiler stack on osx due to
# strict channel priority; disable for rc-phase; don't commit to main!
channel_priority: flexible
conda_forge_output_validation: true
provider: {linux_aarch64: azure, linux_ppc64le: azure}
test_on_native_only: true
os_version:
  linux_64: cos7
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
  error_overlinking: true
